config/routes.rb
Rails.application.routes.draw do
  resources :words
  resources :players
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'switch_team', to: 'games#switch_team'
  post 'add_word', to: 'players#add_word'

  get 'games/:game_id/join', to: 'games#new_join_game', as: 'join_to_game'
  post 'games/:game_id/join', to: 'games#join_game', as: 'join_game'

  get 'games/:game_id/next_turn(/won_turn)', to: 'games#next_turn', as: 'next_turn'

  get 'games/:game_id/start_game', to: 'games#start_game', as: 'start_game'
  root to: 'games#new'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :owner, class_name: 'Player', foreign_key: 'owner'
  has_many :players
  has_many :words
  belongs_to :current_player, class_name: 'Player', foreign_key: 'current_player_id', optional: true
  belongs_to :last_player, class_name: 'Player', foreign_key: 'last_player_id', optional: true

  belongs_to :current_word, class_name: 'Word', foreign_key: 'current_word_id', optional: true

  def pick_next_player
    next_player_team = current_player.team == 1 ? 2 : 1

    next_player = nil
    if last_player.nil?
      next_player = players.find_by(team: next_player_team, position: 0)
    else
      next_position = last_player.position + 1
      next_player = players.find_by(team: next_player_team, position: next_position)
      next_player = players.find_by(team: next_player_team, position: 0) if next_player.nil?
    end
    update(last_player: current_player)
    update(current_player: next_player)
  end

  def set_players_positions
    team1_players = players.where(team: 1)
    team2_players = players.where(team: 2)

    team1_players.each_with_index do |p, i|
      p.update(position: i)
    end

    team2_players.each_with_index do |p, i|
      p.update(position: i)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  def new_join_game; end

  def next_turn
    game = Game.find(params[:game_id])
    won_turn = params[:won_turn]
    player = Player.find(session[:current_player_id])

    if won_turn == 'true'
      game.current_word.update(used: true)
      game.update(t1_score: game.t1_score + 1, current_word: game.words.where(used: false).sample)
    else
      game.update(current_word: game.words.where(used: false).sample)
    end
    game.pick_next_player

    redirect_to game
  end

  def start_game
    game = Game.find(params[:game_id])
    game.set_players_positions
    game.update(
      status: 'round1',
      turn: 0, current_team: 1,
      current_player_id: game.players.find_by(position: 0, team: 1).id,
      t1_score: 0,
      t2_score: 0,
      current_word: game.words.where(used: false).sample
    )

    redirect_to game
  end

  def switch_team
    puts "SESSION #{session[:current_player_id]}"
    player = Player.find(session[:current_player_id])
    player.update(team: player.team == 1 ? 2 : 1)

    redirect_to player.game
  end

  def join_game
    puts("player #{params[:player_name]} is joining game #{params[:game_id]}")

    player = Player.create!(name: params[:player_name], game_id: params[:game_id], team: 1)
    session[:current_player_id] = player.id

    puts "CREATED PLAYER #{player.id} - #{player.name}"

    game = Game.find(params[:game_id])

    redirect_to game
  end

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @player = Player.find(session[:current_player_id])

    @team1 = @game.players.where(team: 1).sort_by(&:position)
    @team2 = @game.players.where(team: 2).sort_by(&:position)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games
  # POST /games.json
  def create
    player = Player.create!(name: game_params[:owner], team: 1)
    session[:current_player_id] = player.id
    @game = Game.new(owner: player, status: 'lobby')

    respond_to do |format|
      if @game.save
        player.update!(game_id: @game.id)
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:owner)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
<% if game.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

  <ul>
    <% game.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label 'Ingresa tu nombre' %>
  <%= form.text_field :owner %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/gameplay.html.erb
<h2></h2>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.owner %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/new_join_game.html.erb
<%= form_tag("", :method => "post") do %>
<%= label_tag(:player_name, "Ingresa tu nombre:") %>
<%= text_field_tag(:player_name) %>
<%= submit_tag("Entrar") %>
<% end %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<% if @game.status == 'lobby' %>
<div class="container hard-border">
  <div class="row">
    <p>
      <strong>Dueño de la sala:</strong>
      <%= @game.owner.name %>
    </p>
  </div>
  <div class="row">
    <p>
      <strong>Link para unirse:</strong>
      <%= join_to_game_url(game_id: @game.id) %>
    </p>
  </div>
</div>

<div class="container">
  <h3>Jugadores: </h3>

  <div class="row">
    <div class="col-sm">
      <h4>Equipo 1</h4>
      <ul>
        <% @game.players.where(team: 1).each do |p| %>
        <li><%= p.name %><% if p.id == @player.id %> (Yo) <% end %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-sm">
      <h4>Equipo 2</h4>
      <ul>
        <% @game.players.where(team: 2).each do |p| %>
        <li><%= p.name %><% if p.id == @player.id %> (Yo) <% end %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div>
    <%= form_tag("/switch_team", :method => "get") do %>
    <%= submit_tag("Cambiar de equipo") %>
    <% end %>
  </div>

  <div class='mt-5'>
    <h5>Ingresa tus palabras/frases</h5>
    <div>
      <%= form_tag("/add_word", :method => "post") do %>
      <%= text_field_tag(:word) %>
      <%= submit_tag("Agregar palabra/frase") %>
      <% end %>
    </div>
    <div>
      <ul>
        <% @player.words.each do |word|%>
        <li> <%= word.text %></li>
        <% end %>
      </ul>
    </div>

    <% if @game.owner.id == @player.id %>
    <div class='mt-5'>
      <%= link_to  "Comenzar juego", start_game_path(game_id: @game.id), as: :button %>
    </div>
    <% else %>
    <p>Esperando a que <%= @game.owner.name %> comience el juego</p>
    <% end %>

  </div>
</div>
<% else %>
<h2> Turno <%= @game.turn %>: Equipo <%= @game.current_team %> </h2>
<h3> Jugando: <%= @game.current_player.name %></h3>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 hard-border">
      <% if @game.current_player.id == @player.id %>
      <h3>Es tu turno, tu palabra es: <strong><%= @game.current_word.text %></strong></h3>
      <div>
        <%= link_to 'LO LOGRE!!', next_turn_path(game_id: @game.id, won_turn: true), :class => "btn" %> |
        <%= link_to 'PASAR', next_turn_path(game_id: @game.id, won_turn: false), :class => "btn btn-danger"%>
      </div>
      <% elsif @game.current_team == @player.team %>
      <h3>Adivina la palabra de <%= @game.current_player.name %></h3>
      <% else %>
      <h3>Está jugando el equipo <%= @game.current_team %>, espera tu turno </h3>
      <% end %>
    </div>
    <div class="col-md-2 hard-border">
      <h5>Equipo 1 <strong><%= @player.team == 1 ? "(Tu equipo)" : "" %></strong>: <%= @game.t1_score %> puntos</h5>
      <ul>
        <% @team1.each do |player| %>
        <li><%= player.name %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-2 hard-border">
      <h5>Equipo 2 <strong><%= @player.team == 2 ? "(Tu equipo)" : "" %></strong>: <%= @game.t2_score %> puntos</h5>
      <ul>
        <% @team2.each do |player|%>
        <li><%= player.name %></li>
        <% end %>
      </ul>
    </div>

  </div>
</div>
<% end %>

<script>
  setTimeout(function() {
    window.location.reload(1);
  }, 6000);
</script>


<!--
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
-->