config/routes.rb
Rails.application.routes.draw do
  resources :words
  resources :players
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'switch_team', to: 'games#switch_team'
  post 'add_word', to: 'players#add_word'

  get 'games/:game_id/join', to: 'games#new_join_game', as: 'join_to_game'
  post 'games/:game_id/join', to: 'games#join_game', as: 'join_game'

  get 'games/:game_id/next_turn(/won_turn)', to: 'games#next_turn', as: 'next_turn'

  get 'games/:game_id/start_game', to: 'games#start_game', as: 'start_game'
  root to: 'games#new'
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:game_id, :text, :player_id)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.text_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.text_field :player_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Text</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.game_id %></td>
        <td><%= word.text %></td>
        <td><%= word.player_id %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @word.game_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @word.text %>
</p>

<p>
  <strong>Player:</strong>
  <%= @word.player_id %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>